defaults:
  - default


# CSWin Transformer, B-224 variant
# ref: https://github.com/microsoft/CSWin-Transformer/blob/main/models/cswin.py
# ref: https://github.com/microsoft/CSWin-Transformer/blob/main/segmentation/configs/cswin/upernet_cswin_base.py

patch_size: 4
embed_dim: 96
depth: [2,4,32,2]
split_size: [1,2,7,7]
num_heads: [4,8,16,32]
mlp_ratio: 4