_target_: yagm.backbones.ForwardIntermediatesTimmBackbone
model_name: convnext_small.fb_in22k_ft_in1k_384  # convnext_nano.r384_ad_in12k | convnext_tiny.fb_in22k_ft_in1k_384 | convnext_small.fb_in22k_ft_in1k_384
pretrained: True
# img_size: ${data.img_size}
in_chans: 3
output_indices: [0, 1, 2, 3]
drop_rate: 0.0
drop_path_rate: 0.0