_target_: yagm.backbones.ForwardIntermediatesTimmBackbone
model_name: maxvit_tiny_tf_512.in1k
pretrained: True
img_size: ${data.img_size}
in_chans: 3
output_indices: [0, 1, 2, 3, 4]
# drop_rate: 0.1
# drop_path_rate: 0.1